Fix "Python is missing" on Ubuntu 20.04
toHero/git-hooks pull request #1
Opened 2021-02-04 09:59 UTC by Rom1P

2021-02-05 14:27 UTC, antitoine requested changes
Merci pour la contribution, regarde mes commentaires :smiley:

2021-02-05 14:27 UTC, antitoine commented on scripts/install.sh
> +# Installing missing python package on Ubuntu 20.04
C'est un peu violant ça, car tu exécute une installation sans l'accord de l'utilisateur.
De plus, si `sudo` demande un mot de passe, ça va tout bloquer.
Autant juste garder le readme (et mettre à jour le wiki redmine également)

2021-02-05 14:27 UTC, antitoine commented on README.md
> +## Python and Ubuntu 20.04
Tu devrais déplacer ton bloc d'instruction en haut, juste avant "# Install" et mettre un truc du genre "# Prerequisite", car c'est pas spécifique à Ubuntu 20.04, il faut Python pour que ça fonctionne (d'ailleurs ça fonctionne avec Python 2.7 ou 3.x il me semble)

2021-02-05 14:45 UTC, Rom1P commented on scripts/install.sh
> +# Installing missing python package on Ubuntu 20.04
Ok du coup j'ai mis à jour le README et le redmine
Pour le sudo il y en a déjà un quelque ligne plus haut donc ca devrait pas poser de soucis non ? Et pour la confirmation j'ai changé le comportement

2021-02-11 08:15 UTC, antitoine approved these changes

2021-02-11 08:16 UTC, merged